
var union   = require('./union');
var classes = require('./classes');

module.exports = [
/* 7 */union(classes.w, classes.dec),
/* 8 */union(classes.w, classes.dec),
/* 9 */union(classes.w, classes.dec),
/*10 */union(classes.w, classes.dec),
/*11 */union(classes.w, classes.dec),
/*12 */union(classes.w, classes.dec),
/*13 */union(classes.w, classes.dec),
/*14 */union(classes.w, classes.dec),
/*15 */union(classes.w, classes.dec),
/*16 */union(classes.w, classes.dec),
/*17 */union(classes.w, classes.dec),
/*18 */union(classes.w, classes.dec),
/*19 */union(classes.w, classes.dec),
/*20 */union(classes.w, classes.dec),
/*21 */union(classes.w, classes.dec),
/*22 */union(classes.w, classes.dec),
/*23 */union(classes.w, classes.dec),
/*24 */union(classes.w, classes.dec),
/*25 */union(classes.w, classes.dec),
/*26 */union(classes.w, classes.dec),
/*27 */union(classes.w, classes.dec),
/*28 */union(classes.w, classes.dec),
/*29 */union(classes.w, classes.dec),
/*30 */union(classes.w, classes.dec),
/*31 */union(classes.w, classes.dec),
/*32 */union(classes.w, classes.dec),
/*33 */union(classes.w, classes.dec),
/*34 */union(classes.w, classes.dec),
/*35 */union(classes.w, classes.dec),
/*36 */union(classes.w, classes.dec),
/*37 */union(classes.w, classes.dec),
/*38 */union(classes.w, classes.dec),
/*39 */union(classes.w, classes.dec),
/*40 */union(classes.w, classes.dec),
/*41 */union(classes.w, classes.dec),
/*42 */union(classes.w, classes.dec),
/*43 */union(classes.w, classes.dec),
/*44 */union(classes.w, classes.dec),
/*45 */union(classes.w, classes.dec),
/*46 */union(classes.w, classes.dec),
/*47 */union(classes.w, classes.dec),
/*48 */union(classes.w, classes.dec),
/*49 */union(classes.w, classes.dec),
/*50 */union(classes.w, classes.dec),
/*51 */union(classes.w, classes.dec),
/*52 */union(classes.w, classes.dec),
/*53 */union(classes.w, classes.dec),
/*54 */union(classes.w, classes.dec),
/*55 */union(classes.w, classes.dec),
/*56 */union(classes.w, classes.dec),
/*57 */union(classes.w, classes.dec),
/*58 */union(classes.w, classes.dec),
/*59 */union(classes.w, classes.dec),
/*60 */union(classes.w, classes.dec),
/*61 */union(classes.w, classes.dec),
/*62 */union(classes.w, classes.dec),
/*63 */union(classes.w, classes.dec),
/*64 */union(classes.w, classes.dec),
/*65 */union(classes.w, classes.dec),
/*66 */union(classes.w, classes.dec),
/*67 */union(classes.w, classes.dec),
/*68 */union(classes.w, classes.dec),
/*69 */union(classes.w, classes.dec),
/*70 */union(classes.w, classes.dec),
/*71 */union(classes.w, classes.dec),
/*72 */union(classes.w, classes.dec),
/*73 */union(classes.w, classes.dec),
/*74 */union(classes.w, classes.dec),
/*75 */union(classes.w, classes.dec),
/*76 */union(classes.w, classes.dec),
/*77 */union(classes.w, classes.dec),
/*78 */union(classes.w, classes.dec),
/*79 */union(classes.w, classes.dec),
/*80 */union(classes.w, classes.dec)
];

module.exports.name = 'master';