
var union   = require('./union');
var classes = require('./classes');

module.exports = [
/* 7 */union(classes.w, classes.dec),
/* 8 */union(classes.w, classes.dec),
/* 9 */union(classes.w, classes.dec),
/*10 */union(classes.w, classes.dec),
/*11 */union(classes.w, classes.dec),
/*12 */union(classes.w, classes.dec),
/*13 */union(classes.w, classes.dec),
/*14 */union(classes.w, classes.dec),
/*15 */union(classes.w, classes.dec),
/*16 */union(classes.w, classes.dec),
/*17 */union(classes.w, classes.dec),
/*18 */union(classes.w, classes.dec),
/*19 */union(classes.w, classes.dec),
/*20 */union(classes.w, classes.dec),
/*21 */union(classes.w, classes.dec),
/*22 */union(classes.w, classes.dec),
/*23 */union(classes.w, classes.dec),
/*24 */union(classes.w, classes.dec),
/*25 */union(classes.w, classes.dec),
/*26 */union(classes.w, classes.dec),
/*27 */union(classes.w, classes.dec),
/*28 */union(classes.w, classes.dec),
/*29 */union(classes.w, classes.dec),
/*30 */union(classes.w, classes.dec),
/*31 */union(classes.w, classes.dec),
/*32 */classes.w,
/*33 */classes.w,
/*34 */classes.w,
/*35 */classes.w,
/*36 */classes.w,
/*37 */classes.w,
/*38 */classes.w,
/*39 */classes.w,
/*40 */classes.w,
/*41 */classes.w,
/*42 */classes.w,
/*43 */classes.w,
/*44 */classes.w,
/*45 */classes.w,
/*46 */classes.w,
/*47 */classes.w,
/*48 */classes.w,
/*49 */classes.w,
/*50 */classes.w,
/*51 */classes.w,
/*52 */classes.w,
/*53 */classes.w,
/*54 */classes.w,
/*55 */classes.w,
/*56 */classes.w,
/*57 */classes.w,
/*58 */classes.w,
/*59 */classes.w,
/*60 */classes.w,
/*61 */classes.w,
/*62 */classes.w,
/*63 */classes.w,
/*64 */classes.w,
/*65 */classes.w,
/*66 */classes.w,
/*67 */classes.w,
/*68 */classes.w,
/*69 */classes.w,
/*70 */classes.w,
/*71 */classes.w,
/*72 */classes.w,
/*73 */classes.w,
/*74 */classes.w,
/*75 */classes.w,
/*76 */classes.w,
/*77 */classes.w,
/*78 */classes.w,
/*79 */classes.w,
/*80 */classes.w
];

module.exports.name = 'conect';