
var union   = require('./union');
var classes = require('./classes');

module.exports = [
/* 7 */classes.w,
/* 8 */classes.w,
/* 9 */classes.w,
/*10 */classes.w,
/*11 */union(classes.dec, classes.w),
/*12 */union(classes.dec, classes.w),
/*13 */union(classes.dec, classes.w),
/*14 */union(classes.dec, classes.w),
/*15 */classes.w,
/*16 */classes.w,
/*17 */classes.w,
/*18 */classes.w,
/*19 */classes.w,
/*20 */classes.w,
/*21 */classes.w,
/*22 */classes.w,
/*23 */classes.w,
/*24 */classes.w,
/*25 */classes.w,
/*26 */classes.w,
/*27 */classes.w,
/*28 */classes.w,
/*29 */classes.w,
/*30 */classes.w,
/*31 */classes.w,
/*32 */classes.w,
/*33 */classes.w,
/*34 */classes.w,
/*35 */classes.w,
/*36 */classes.w,
/*37 */classes.w,
/*38 */classes.w,
/*39 */classes.w,
/*40 */classes.w,
/*41 */classes.w,
/*42 */classes.w,
/*43 */classes.w,
/*44 */classes.w,
/*45 */classes.w,
/*46 */classes.w,
/*47 */classes.w,
/*48 */classes.w,
/*49 */classes.w,
/*50 */classes.w,
/*51 */classes.w,
/*52 */classes.w,
/*53 */classes.w,
/*54 */classes.w,
/*55 */classes.w,
/*56 */classes.w,
/*57 */classes.w,
/*58 */classes.w,
/*59 */classes.w,
/*60 */classes.w,
/*61 */classes.w,
/*62 */classes.w,
/*63 */classes.w,
/*64 */classes.w,
/*65 */classes.w,
/*66 */classes.w,
/*67 */classes.w,
/*68 */classes.w,
/*69 */classes.w,
/*70 */classes.w,
/*71 */classes.w,
/*72 */classes.w,
/*73 */classes.w,
/*74 */classes.w,
/*75 */classes.w,
/*76 */classes.w,
/*77 */classes.w,
/*78 */classes.w,
/*79 */classes.w,
/*80 */classes.w
];

module.exports.name = 'model';