
var union   = require('../util').object_concat;
var classes = require('./classes');

module.exports = [
/* 1 */[union(classes.e), '_'],
/* 2 */[union(classes.n), '_'],
/* 3 */[union(classes.d), '_'],
/* 4 */[union(classes.m), '_'],
/* 5 */[union(classes.d), '_'],
/* 6 */[union(classes.l), '_'],
/* 7 */[union(classes.w), '_'],
/* 8 */[union(classes.w), '_'],
/* 9 */[union(classes.w), '_'],
/*10 */[union(classes.w), '_'],
/*11 */[union(classes.w), '_'],
/*12 */[union(classes.w), '_'],
/*13 */[union(classes.w), '_'],
/*14 */[union(classes.w), '_'],
/*15 */[union(classes.w), '_'],
/*16 */[union(classes.w), '_'],
/*17 */[union(classes.w), '_'],
/*18 */[union(classes.w), '_'],
/*19 */[union(classes.w), '_'],
/*20 */[union(classes.w), '_'],
/*21 */[union(classes.w), '_'],
/*22 */[union(classes.w), '_'],
/*23 */[union(classes.w), '_'],
/*24 */[union(classes.w), '_'],
/*25 */[union(classes.w), '_'],
/*26 */[union(classes.w), '_'],
/*27 */[union(classes.w), '_'],
/*28 */[union(classes.w), '_'],
/*29 */[union(classes.w), '_'],
/*30 */[union(classes.w), '_'],
/*31 */[union(classes.w), '_'],
/*32 */[union(classes.w), '_'],
/*33 */[union(classes.w), '_'],
/*34 */[union(classes.w), '_'],
/*35 */[union(classes.w), '_'],
/*36 */[union(classes.w), '_'],
/*37 */[union(classes.w), '_'],
/*38 */[union(classes.w), '_'],
/*39 */[union(classes.w), '_'],
/*40 */[union(classes.w), '_'],
/*41 */[union(classes.w), '_'],
/*42 */[union(classes.w), '_'],
/*43 */[union(classes.w), '_'],
/*44 */[union(classes.w), '_'],
/*45 */[union(classes.w), '_'],
/*46 */[union(classes.w), '_'],
/*47 */[union(classes.w), '_'],
/*48 */[union(classes.w), '_'],
/*49 */[union(classes.w), '_'],
/*50 */[union(classes.w), '_'],
/*51 */[union(classes.w), '_'],
/*52 */[union(classes.w), '_'],
/*53 */[union(classes.w), '_'],
/*54 */[union(classes.w), '_'],
/*55 */[union(classes.w), '_'],
/*56 */[union(classes.w), '_'],
/*57 */[union(classes.w), '_'],
/*58 */[union(classes.w), '_'],
/*59 */[union(classes.w), '_'],
/*60 */[union(classes.w), '_'],
/*61 */[union(classes.w), '_'],
/*62 */[union(classes.w), '_'],
/*63 */[union(classes.w), '_'],
/*64 */[union(classes.w), '_'],
/*65 */[union(classes.w), '_'],
/*66 */[union(classes.w), '_'],
/*67 */[union(classes.w), '_'],
/*68 */[union(classes.w), '_'],
/*69 */[union(classes.w), '_'],
/*70 */[union(classes.w), '_'],
/*71 */[union(classes.w), '_'],
/*72 */[union(classes.w), '_'],
/*73 */[union(classes.w), '_'],
/*74 */[union(classes.w), '_'],
/*75 */[union(classes.w), '_'],
/*76 */[union(classes.w), '_'],
/*77 */[union(classes.w), '_'],
/*78 */[union(classes.w), '_'],
/*79 */[union(classes.w), '_'],
/*80 */[union(classes.w), '_'],
];

module.exports.name = 'endmdl';