var classes = require('./classes');

module.exports = [
/* 1 */[classes.m, '_'],
/* 2 */[classes.o, '_'],
/* 3 */[classes.d, '_'],
/* 4 */[classes.e, '_'],
/* 5 */[classes.l, '_'],
/* 6 */[classes.w, '_'],
/* 7 */[classes.w, '_'],
/* 8 */[classes.w, '_'],
/* 9 */[classes.w, '_'],
/*10 */[classes.w, '_'],
/*11 */[classes.dec.concat(classes.w), 'model'],
/*12 */[classes.dec.concat(classes.w), 'model'],
/*13 */[classes.dec.concat(classes.w), 'model'],
/*14 */[classes.w, '_'],
/*15 */[classes.w, '_'],
/*16 */[classes.w, '_'],
/*17 */[classes.w, '_'],
/*18 */[classes.w, '_'],
/*19 */[classes.w, '_'],
/*20 */[classes.w, '_'],
/*21 */[classes.w, '_'],
/*22 */[classes.w, '_'],
/*23 */[classes.w, '_'],
/*24 */[classes.w, '_'],
/*25 */[classes.w, '_'],
/*26 */[classes.w, '_'],
/*27 */[classes.w, '_'],
/*28 */[classes.w, '_'],
/*29 */[classes.w, '_'],
/*30 */[classes.w, '_'],
/*31 */[classes.w, '_'],
/*32 */[classes.w, '_'],
/*33 */[classes.w, '_'],
/*34 */[classes.w, '_'],
/*35 */[classes.w, '_'],
/*36 */[classes.w, '_'],
/*37 */[classes.w, '_'],
/*38 */[classes.w, '_'],
/*39 */[classes.w, '_'],
/*40 */[classes.w, '_'],
/*41 */[classes.w, '_'],
/*42 */[classes.w, '_'],
/*43 */[classes.w, '_'],
/*44 */[classes.w, '_'],
/*45 */[classes.w, '_'],
/*46 */[classes.w, '_'],
/*47 */[classes.w, '_'],
/*48 */[classes.w, '_'],
/*49 */[classes.w, '_'],
/*50 */[classes.w, '_'],
/*60 */[classes.w, '_'],
/*61 */[classes.w, '_'],
/*62 */[classes.w, '_'],
/*63 */[classes.w, '_'],
/*64 */[classes.w, '_'],
/*65 */[classes.w, '_'],
/*66 */[classes.w, '_'],
/*67 */[classes.w, '_'],
/*68 */[classes.w, '_'],
/*69 */[classes.w, '_'],
/*70 */[classes.w, '_'],
/*71 */[classes.w, '_'],
/*72 */[classes.w, '_'],
/*73 */[classes.w, '_'],
/*74 */[classes.w, '_'],
/*75 */[classes.w, '_'],
/*76 */[classes.w, '_'],
/*77 */[classes.w, '_'],
/*78 */[classes.w, '_'],
/*79 */[classes.w, '_'],
/*80 */[classes.w, '_'],
];