
var classes = require('./classes');

module.exports = [
/* 7 */classes.whatever,
/* 8 */classes.whatever,
/* 9 */classes.whatever,
/*10 */classes.whatever,
/*11 */classes.whatever,
/*12 */classes.whatever,
/*13 */classes.whatever,
/*14 */classes.whatever,
/*15 */classes.whatever,
/*16 */classes.whatever,
/*17 */classes.whatever,
/*18 */classes.whatever,
/*19 */classes.whatever,
/*20 */classes.whatever,
/*21 */classes.whatever,
/*22 */classes.whatever,
/*23 */classes.whatever,
/*24 */classes.whatever,
/*25 */classes.whatever,
/*26 */classes.whatever,
/*27 */classes.whatever,
/*28 */classes.whatever,
/*29 */classes.whatever,
/*30 */classes.whatever,
/*31 */classes.whatever,
/*32 */classes.whatever,
/*33 */classes.whatever,
/*34 */classes.whatever,
/*35 */classes.whatever,
/*36 */classes.whatever,
/*37 */classes.whatever,
/*38 */classes.whatever,
/*39 */classes.whatever,
/*40 */classes.whatever,
/*41 */classes.whatever,
/*42 */classes.whatever,
/*43 */classes.whatever,
/*44 */classes.whatever,
/*45 */classes.whatever,
/*46 */classes.whatever,
/*47 */classes.whatever,
/*48 */classes.whatever,
/*49 */classes.whatever,
/*50 */classes.whatever,
/*51 */classes.whatever,
/*52 */classes.whatever,
/*53 */classes.whatever,
/*54 */classes.whatever,
/*55 */classes.whatever,
/*56 */classes.whatever,
/*57 */classes.whatever,
/*58 */classes.whatever,
/*59 */classes.whatever,
/*60 */classes.whatever,
/*61 */classes.whatever,
/*62 */classes.whatever,
/*63 */classes.whatever,
/*64 */classes.whatever,
/*65 */classes.whatever,
/*66 */classes.whatever,
/*67 */classes.whatever,
/*68 */classes.whatever,
/*69 */classes.whatever,
/*70 */classes.whatever,
/*71 */classes.whatever,
/*72 */classes.whatever,
/*73 */classes.whatever,
/*74 */classes.whatever,
/*75 */classes.whatever,
/*76 */classes.whatever,
/*77 */classes.whatever,
/*78 */classes.whatever,
/*79 */classes.whatever,
/*80 */classes.whatever];
module.exports.name = 'skip';